micro:

  frontend:
    image:
      repository: eu.gcr.io/gcp_project_id_12345/geo-python-rivers-frontend
      tag: v1.0.0
    service:
      type: NodePort
      nodePort: 32767

  backend:
    image:
      repository: eu.gcr.io/gcp_project_id_12345/geo-python-rivers-backend
      tag: v1.0.0
    service:
      type: NodePort
      nodePort: 32766
    readinessEnabled: true
    readiness:
      path: /api/alive
    environment:
      DATABASE_HOST: "database"
      DATABASE_NAME: "apidb"
      DATABASE_USER: "apiuser"
      DATABASE_PASSWORD: "SecretPassword123!"

ingress:
  enabled: true
  paths:
    - path: /
      service: geo-python-rivers-frontend
    - path: /*
      service: geo-python-rivers-frontend

    - path: /api/
      service: geo-python-rivers-backend
    - path: /api/*
      service: geo-python-rivers-backend

