airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
  usersUpdate: true

ingress:
  enabled: true
  web:
    path: ""
