micro:

  frontend:
    image:
      repository: eu.gcr.io/gcp_project_id_12345/postmortem-frontend
      tag: v1.0.0
    service:
      type: NodePort
      nodePort: 32767

  backend:
    image:
      repository: eu.gcr.io/gcp_project_id_12345/postmortem-backend
      tag: v1.0.0
    service:
      type: NodePort
      nodePort: 32766
    readinessEnabled: true
    readiness:
      path: /api/alive

ingress:
  enabled: true
  paths:
    - path: /
      service: postmortem-frontend
    - path: /*
      service: postmortem-frontend

    - path: /api/
      service: postmortem-backend
    - path: /api/*
      service: postmortem-backend

  annotations:
    kubernetes.io/ingress.global-static-ip-name: postmortem-global-address

